config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount EffectiveClassifieds::Engine => '/', as: 'effective_classifieds'
end

EffectiveClassifieds::Engine.routes.draw do
  # Public routes
  scope module: 'effective' do
    resources :classifieds, only: [:index, :show, :edit, :update]
    resources :jobs, only: [:index, :show, :edit, :update], controller: 'classifieds'

    resources :classified_wizards, only: [:new, :show, :destroy] do
      resources :build, controller: :classified_wizards, only: [:show, :update]
    end

  end

  namespace :admin do
    resources :classifieds, except: [:show] do
      post :approve, on: :member
      post :unapprove, on: :member
    end

    resources :jobs, except: [:show], controller: 'classifieds'
  end

end

app/models/effective/classified.rb
# frozen_string_literal: true

module Effective
  class Classified < ActiveRecord::Base
    self.table_name = (EffectiveClassifieds.classifieds_table_name || :classifieds).to_s

    attr_accessor :current_user
    attr_accessor :importing

    acts_as_slugged
    acts_as_purchasable
    log_changes if respond_to?(:log_changes)
    acts_as_trackable if respond_to?(:acts_as_trackable)
    acts_as_role_restricted if respond_to?(:acts_as_role_restricted)

    # This will be the owner of the classified ad submission
    # Or the admin user that created it
    belongs_to :owner, polymorphic: true

    # When submitted through the wizard
    belongs_to :classified_wizard, polymorphic: true, optional: true

    has_one_attached :file
    has_one_purgable :file

    has_rich_text :body

    acts_as_statused(
      :draft,       # Initial state
      :submitted,   # Once submitted by the classified ad submission.
      :approved     # Exit state. Classified was approved.
    )

    effective_resource do
      title              :string
      category           :string

      organization       :string    # Or seller
      location           :string

      website            :string
      email              :string
      phone              :string

      # Logic
      start_on           :date
      end_on             :date

      # Acts as Slugged
      slug               :string

      # Acts as Statused
      status                 :string, permitted: false
      status_steps           :text, permitted: false

      # Access
      roles_mask         :integer
      authenticate_user  :boolean

      archived           :boolean

      price         :integer
      tax_exempt    :boolean
      qb_item_name  :string

      timestamps
    end

    scope :sorted, -> { order(start_on: :desc) }

    scope :deep, -> { 
      with_rich_text_body.with_attached_file.includes(:classified_wizard, :owner, :purchased_order) 
    }

    scope :upcoming, -> { where(arel_table[:end_on].gt(Time.zone.now)) }
    scope :past, -> { where(arel_table[:end_on].lteq(Time.zone.now)) }

    scope :unarchived, -> { where(archived: false) }
    scope :archived, -> { where(archived: true) }

    scope :published, -> {
      approved
      .unarchived
      .where(arel_table[:start_on].lteq(Time.zone.now))
      .where(arel_table[:end_on].gt(Time.zone.now))
    }

    scope :paginate, -> (page: nil, per_page: nil) {
      page = (page || 1).to_i
      offset = [(page - 1), 0].max * (per_page || EffectiveClassifieds.per_page)

      limit(per_page).offset(offset)
    }

    scope :classifieds, -> (user: nil, unpublished: false) {
      scope = all.deep

      if defined?(EffectiveRoles) && EffectiveClassifieds.use_effective_roles
        scope = scope.for_role(user&.roles)
      end

      if user.blank?
        scope = scope.where(authenticate_user: false)
      end

      unless unpublished
        scope = scope.published
      end

      scope
    }

    before_validation(if: -> { current_user.present? }) do
      self.owner ||= current_user
    end

    before_validation(if: -> { EffectiveClassifieds.default_qb_item_name.present? }) do
      assign_attributes(qb_item_name: EffectiveClassifieds.default_qb_item_name) if qb_item_name.blank?
    end

    # Automatically approve submissions created by admins outside the submissions wizard
    before_validation(if: -> { new_record? && classified_wizard.blank? }) do
      assign_attributes(status: :approved, price: 0)
    end

    validates :title, presence: true, length: { maximum: 200 }
    validates :category, presence: true
    validates :body, presence: true

    validates :start_on, presence: true
    validates :end_on, presence: true

    with_options(unless: -> { importing }) do
      validates :location, presence: true
      validates :organization, presence: true
      validates :email, presence: true
      validates :phone, presence: true
      validates :contact_name, presence: true
    end

    validate(if: -> { start_on.present? && end_on.present? && !importing }) do
      self.errors.add(:end_on, 'must be after start date') if end_on < start_on
    end

    def end_on_distance
      date = Time.zone.now
      ApplicationController.helpers.distance_of_time_in_words(date + EffectiveClassifieds.max_duration, date).gsub('about', '').strip
    end

    validate(if: -> { start_on.present? && end_on.present? && EffectiveClassifieds.max_duration.present? && !importing }) do
      if (end_on - start_on) > EffectiveClassifieds.max_duration
        self.errors.add(:end_on, "must be within #{end_on_distance} of start date")
      end
    end

    validate(if: -> { category.present? }) do
      self.errors.add(:category, 'is invalid') unless Array(EffectiveClassifieds.categories).include?(category)
    end

    validate(if: -> { file.attached? && !Rails.env.test? }) do
      self.errors.add(:file, 'expected a .pdf file') unless file.content_type == 'application/pdf'
    end

    def to_s
      title.presence || model_name.human
    end

    def for_json
      { id: id, title: title, body: body.to_s, created_at: created_at, updated_at: updated_at }
    end

    def purchasable_name
      "#{category} - #{title}"
    end

    def published?
      return false unless approved?
      return false if archived?
      return false if start_on.blank? || (Time.zone.now < start_on)
      return false if end_on.present? && (Time.zone.now >= end_on)
      true
    end

    def submit!
      submitted!
      approve! if EffectiveClassifieds.auto_approve

      after_commit do
        EffectiveClassifieds.send_email(:classified_submitted, self)
      end

      true
    end

    def approve!
      approved!
    end

    def unapprove!
      unapproved!
    end

  end
end

app/models/effective/classified_wizard.rb
module Effective
  class ClassifiedWizard < ActiveRecord::Base
    self.table_name = (EffectiveClassifieds.classified_wizards_table_name || :classified_wizards).to_s

    effective_classifieds_classified_wizard
  end
end

app/controllers/admin/classified_wizards_controller.rb
module Admin
  class ClassifiedWizardsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)
    before_action { EffectiveResources.authorize!(self, :admin, :effective_classifieds) }

    include Effective::CrudController

    resource_scope -> { EffectiveEvents.ClassifiedWizard.deep.all }
    datatable -> { Admin::EffectiveClassifiedWizardsDatatable.new }

    private

    def permitted_params
      model = (params.key?(:effective_classified_wizard) ? :effective_classified_wizard : :classified_wizard)
      params.require(model).permit!
    end

  end
end

app/controllers/effective/classified_submissions_controller.rb
module Effective
  class ClassifiedSubmissionsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)

    include Effective::WizardController

    resource_scope -> { EffectiveClassifieds.ClassifiedSubmission.deep.where(owner: current_user) }

    # Allow only 1 in-progress application at a time
    before_action(only: [:new, :show], unless: -> { resource&.done? }) do
      existing = resource_scope.in_progress.where.not(id: resource).first

      if existing.present?
        flash[:success] = "You have been redirected to your in-progress classified ad submission"
        redirect_to effective_classifieds.classified_submission_build_path(existing, existing.next_step)
      end
    end

    after_save do
      flash.now[:success] = ''
    end

    private

    def permitted_params
      model = (params.key?(:effective_classified_submission) ? :effective_classified_submission : :classified_submission)
      params.require(model).permit!.except(:status, :status_steps, :wizard_steps, :submitted_at)
    end

  end
end

app/controllers/effective/classified_wizards_controller.rb
module Effective
  class ClassifiedWizardsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)

    include Effective::WizardController

    resource_scope -> { EffectiveClassifieds.ClassifiedWizard.deep.where(owner: current_user) }

  end
end

app/controllers/effective/classifieds_controller.rb
module Effective
  class ClassifiedsController < ApplicationController
    include Effective::CrudController

    def index
      EffectiveResources.authorize!(self, :index, ::Effective::Classified)

      @page_title ||= view_context.classifieds_name_label

      @classifieds = ::Effective::Classified.classifieds(user: current_user).sorted
    end

    def show
      @classified = resource_scope.find(params[:id])

      if @classified.respond_to?(:roles_permit?)
        raise Effective::AccessDenied.new('Access Denied', :show, @classified) unless @classified.roles_permit?(current_user)
      end

      EffectiveResources.authorize!(self, :show, @classified)

      if EffectiveResources.authorized?(self, :admin, :effective_classifieds)
        flash.now[:warning] = [
          'Hi Admin!',
          ("You are viewing a hidden #{view_context.classified_label.downcase}." unless @classified.published?),
          ("<a href='#{effective_classifieds.edit_admin_classified_path(@classified)}' class='alert-link'>Edit this #{view_context.classified_label.downcase}</a>.")
        ].compact.join(' ')
      end

      @page_title ||= @classified.to_s

      respond_to do |format|
        format.html { }

        format.json {
          url = effective_classifieds.classified_url(@classified, format: :json)
          render(json: @classified.for_json.merge(url: url).to_json)
        }
      end
    end

    private

    def permitted_params
      params.require(:effective_classified).except(:status, :status_steps).permit!
    end

  end
end

app/views/effective/classified_wizards/_additional_fields.html.haml
- # Intentionally Blank

app/views/effective/classified_wizards/_classified.html.haml
.card
  .card-body
    .row
      .col-sm
        %h5.card-title= classified_wizard.wizard_step_title(:classified)
      .col-sm-auto.text-right
        = link_to('Edit', wizard_path(:classified)) if edit_effective_wizard?

    - classified = classified_wizard.classified
    = render 'effective/classifieds/summary', classified: classified

app/views/effective/classified_wizards/_classified_wizard.html.haml
.effective-classified-wizard
  - classified_wizard.render_steps.each do |partial|
    = render "effective/classified_wizards/#{partial}", classified_wizard: classified_wizard, step: partial

app/views/effective/classified_wizards/_content.html.haml
-# Intentionally blank

app/views/effective/classified_wizards/_dashboard.html.haml
- if can?(:new, EffectiveClassifieds.ClassifiedWizard)

  -# In-progress submission
  - submission = EffectiveClassifieds.ClassifiedWizard.in_progress.for(current_user).first
  - datatable = EffectiveResources.best('EffectiveClassifiedWizardsDatatable').new(self, namespace: :effective)

  - if submission.present?
    %h2 In-progress #{classifieds_label}

    %p Your submission is incomplete:

    %p
      Please
      = link_to("Continue submission", effective_classifieds.classified_wizard_build_path(submission, submission.next_step), 'data-turbolinks' => false, class: 'btn btn-primary')
      or you can
      = link_to('Abandon submission', effective_classifieds.classified_wizard_path(submission), 'data-confirm': "Really delete #{submission}?", 'data-method': :delete, class: 'btn btn-danger')
      to submit another.

    %hr

  %h2= classifieds_label

  - if datatable.present?
    = render_simple_datatable(datatable)
  - else
    %p You don't have any #{classifieds_label.downcase}. When you do, we'll show them here.

  - if submission.blank?
    %p= link_to "Post a #{classified_label}", effective_classifieds.new_classified_wizard_path, class: 'btn btn-primary'

app/views/effective/classified_wizards/_layout.html.haml
.row
  .col-lg-3.mb-3= render_wizard_sidebar(resource)
  .col-lg-9.pb-3= yield

app/views/effective/classified_wizards/_orders.html.haml
- if classified_wizard.submit_order&.purchased?
  .card.mb-4
    .card-body
      = render(classified_wizard.submit_order)

app/views/effective/classified_wizards/_summary.html.haml
- classified = classified_wizard.classified

%table.table.table-sm
  %tbody
    %tr
      %th.border-0= classified_label
      %td.border-0

        - if classified&.published?
          = link_to(classified, effective_classifieds.classified_path(classified), target: '_blank')
        - else
          = classified.presence || "#{classified_label} was deleted"

    - if request.path.start_with?('/admin')
      %tr
        %th Submitted by
        %td
          - url = (polymorphic_admin_path(classified_wizard.owner) rescue "/admin/users/#{classified_wizard.owner.to_param}/edit")
          = link_to(classified_wizard.owner, url)
    - else
      %tr
        %th Submitted by
        %td= classified_wizard.owner

    - if classified&.was_submitted?
      %tr
        %th Status
        %td
          %span.badge.badge-secondary= classified.status

    - if classified_wizard.price_category.present?
      %tr
        %th Price Category
        %td= classified_wizard.price_category

    - if classified_wizard.user.present?
      %tr
        %th Member
        %td
          = classified_wizard.user
          %small= masked_email(classified_wizard.user)

app/views/effective/classified_wizards/billing.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  - raise('expected owner to respond to billing_address') unless resource.owner.respond_to?(:billing_address)

  = card do
    = effective_form_with(model: resource, url: wizard_path(step), method: :put) do |f|
      = f.hidden_field :id

      = f.fields_for(:owner, f.object.owner) do |fo|
        = effective_address_fields(fo, :billing)

      %p.text-muted * Not all #{classified_label} require a fee. We ask for your billing address for future use.

      = f.save 'Save and Continue'

app/views/effective/classified_wizards/checkout.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  = card do
    = render_checkout_step2(resource.submit_order, purchased_url: wizard_path(:submitted), deferred_url: wizard_path(:checkout), declined_url: wizard_path(:checkout), skip_deferred: EffectiveClassifieds.skip_deferred)

app/views/effective/classified_wizards/classified.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  .card
    .card-body
      = effective_form_with(model: resource, url: wizard_path(step), method: :put) do |f|
        = f.hidden_field :id

        = f.fields_for :classifieds, (f.object.classified || f.object.build_classified) do |fc|
          = fc.hidden_field :id

          = fc.hidden_field :owner_id, value: f.object.owner_id
          = fc.hidden_field :owner_type, value: f.object.owner_type

          = render('effective/classifieds/fields', f: fc, classified: fc.object)

        = render('effective/classified_wizards/additional_fields', f: f, classified_wizard: f.object)

        = f.save 'Save and Continue'

app/views/effective/classified_wizards/start.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  .card
    .card-body
      %p Welcome #{current_user}!

      %p
        You can use this wizard to submit a new #{classified_label.downcase} for display on the #{classifieds_name_label}.
        Your progress will be saved as you move through the wizard.
        Once your posting is published you are able to come back and edit the details.

      = effective_form_with(model: resource, url: wizard_path(step), method: :put) do |f|
        = f.hidden_field :id

        = f.hidden_field :owner_type
        = f.hidden_field :owner_id

        = f.save 'Save and Continue'

app/views/effective/classified_wizards/submitted.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  - classified = resource.classified

  - raise('expected a submitted classified_wizard') unless resource.was_submitted?
  - raise('expected a submitted classified') unless classified.was_submitted?

  - if resource.checkout_required?
    - raise('expected a purchased classified submit_order') unless resource.submit_order&.purchased?

  .alert.alert-success.mb-4
    This #{classified_label.downcase} was submitted on #{classified.submitted_at.strftime('%F')}.

  - unless classified.approved?
    .alert.alert-warning.mb-4
      Your #{classified_label.downcase} must still be approved before it will be displayed.

  .mb-4= link_to "Return to Dashboard", return_to_dashboard_path, class: 'btn btn-lg btn-primary btn-block'

  = card do
    = render 'effective/classified_wizards/summary', classified_wizard: resource

  = render 'effective/classified_wizards/classified_wizard', classified_wizard: resource

  - if resource.orders.present?
    .mb-4
      = collapse('Show orders...', card_class: 'my-2') do
        = render 'effective/classified_wizards/orders', classified_wizard: resource

  = link_to "Return to Dashboard", return_to_dashboard_path, class: 'btn btn-lg btn-primary btn-block'

app/views/effective/classified_wizards/summary.html.haml
= render 'layout' do
  = render 'effective/classified_wizards/content', resource: resource

  = render('effective/classified_wizards/classified_wizard', classified_wizard: resource)

  = effective_form_with(model: resource, url: wizard_path(step), method: :put) do |f|
    = f.hidden_field :id
    = f.submit "Save and Continue", class: 'btn btn-primary'