config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount EffectiveClassifieds::Engine => '/', as: 'effective_classifieds'
end

EffectiveClassifieds::Engine.routes.draw do
  # Public routes
  scope module: 'effective' do
    resources :classifieds, only: [:index, :show, :edit, :update]
    resources :jobs, only: [:index, :show, :edit, :update], controller: 'classifieds'

    resources :classified_wizards, only: [:new, :show, :destroy] do
      resources :build, controller: :classified_wizards, only: [:show, :update]
    end

  end

  namespace :admin do
    resources :classifieds, except: [:show] do
      post :approve, on: :member
      post :unapprove, on: :member
    end

    resources :jobs, except: [:show], controller: 'classifieds'
  end

end

app/models/effective/classified.rb
# frozen_string_literal: true

module Effective
  class Classified < ActiveRecord::Base
    self.table_name = (EffectiveClassifieds.classifieds_table_name || :classifieds).to_s

    attr_accessor :current_user
    attr_accessor :importing

    acts_as_slugged
    acts_as_purchasable
    log_changes if respond_to?(:log_changes)
    acts_as_trackable if respond_to?(:acts_as_trackable)
    acts_as_role_restricted if respond_to?(:acts_as_role_restricted)

    # This will be the owner of the classified ad submission
    # Or the admin user that created it
    belongs_to :owner, polymorphic: true

    # When submitted through the wizard
    belongs_to :classified_wizard, polymorphic: true, optional: true

    has_one_attached :file
    has_one_purgable :file

    has_rich_text :body

    acts_as_statused(
      :draft,       # Initial state
      :submitted,   # Once submitted by the classified ad submission.
      :approved     # Exit state. Classified was approved.
    )

    effective_resource do
      title              :string
      category           :string

      organization       :string    # Or seller
      location           :string

      website            :string
      email              :string
      phone              :string

      # Logic
      start_on           :date
      end_on             :date

      # Acts as Slugged
      slug               :string

      # Acts as Statused
      status                 :string, permitted: false
      status_steps           :text, permitted: false

      # Access
      roles_mask         :integer
      authenticate_user  :boolean

      archived           :boolean

      price         :integer
      tax_exempt    :boolean
      qb_item_name  :string

      timestamps
    end

    scope :sorted, -> { order(start_on: :desc) }

    scope :deep, -> { 
      with_rich_text_body.with_attached_file.includes(:classified_wizard, :owner, :purchased_order) 
    }

    scope :upcoming, -> { where(arel_table[:end_on].gt(Time.zone.now)) }
    scope :past, -> { where(arel_table[:end_on].lteq(Time.zone.now)) }

    scope :unarchived, -> { where(archived: false) }
    scope :archived, -> { where(archived: true) }

    scope :published, -> {
      approved
      .unarchived
      .where(arel_table[:start_on].lteq(Time.zone.now))
      .where(arel_table[:end_on].gt(Time.zone.now))
    }

    scope :paginate, -> (page: nil, per_page: nil) {
      page = (page || 1).to_i
      offset = [(page - 1), 0].max * (per_page || EffectiveClassifieds.per_page)

      limit(per_page).offset(offset)
    }

    scope :classifieds, -> (user: nil, unpublished: false) {
      scope = all.deep

      if defined?(EffectiveRoles) && EffectiveClassifieds.use_effective_roles
        scope = scope.for_role(user&.roles)
      end

      if user.blank?
        scope = scope.where(authenticate_user: false)
      end

      unless unpublished
        scope = scope.published
      end

      scope
    }

    before_validation(if: -> { current_user.present? }) do
      self.owner ||= current_user
    end

    before_validation(if: -> { EffectiveClassifieds.default_qb_item_name.present? }) do
      assign_attributes(qb_item_name: EffectiveClassifieds.default_qb_item_name) if qb_item_name.blank?
    end

    # Automatically approve submissions created by admins outside the submissions wizard
    before_validation(if: -> { new_record? && classified_wizard.blank? }) do
      assign_attributes(status: :approved, price: 0)
    end

    validates :title, presence: true, length: { maximum: 200 }
    validates :category, presence: true
    validates :body, presence: true

    validates :start_on, presence: true
    validates :end_on, presence: true

    with_options(unless: -> { importing }) do
      validates :location, presence: true
      validates :organization, presence: true
      validates :email, presence: true
      validates :phone, presence: true
      validates :contact_name, presence: true
    end

    validate(if: -> { start_on.present? && end_on.present? && !importing }) do
      self.errors.add(:end_on, 'must be after start date') if end_on < start_on
    end

    def end_on_distance
      date = Time.zone.now
      ApplicationController.helpers.distance_of_time_in_words(date + EffectiveClassifieds.max_duration, date).gsub('about', '').strip
    end

    validate(if: -> { start_on.present? && end_on.present? && EffectiveClassifieds.max_duration.present? && !importing }) do
      if (end_on - start_on) > EffectiveClassifieds.max_duration
        self.errors.add(:end_on, "must be within #{end_on_distance} of start date")
      end
    end

    validate(if: -> { category.present? }) do
      self.errors.add(:category, 'is invalid') unless Array(EffectiveClassifieds.categories).include?(category)
    end

    validate(if: -> { file.attached? && !Rails.env.test? }) do
      self.errors.add(:file, 'expected a .pdf file') unless file.content_type == 'application/pdf'
    end

    def to_s
      title.presence || model_name.human
    end

    def for_json
      { id: id, title: title, body: body.to_s, created_at: created_at, updated_at: updated_at }
    end

    def purchasable_name
      "#{category} - #{title}"
    end

    def published?
      return false unless approved?
      return false if archived?
      return false if start_on.blank? || (Time.zone.now < start_on)
      return false if end_on.present? && (Time.zone.now >= end_on)
      true
    end

    def submit!
      submitted!
      approve! if EffectiveClassifieds.auto_approve

      after_commit do
        EffectiveClassifieds.send_email(:classified_submitted, self)
      end

      true
    end

    def approve!
      approved!
    end

    def unapprove!
      unapproved!
    end

  end
end

app/models/effective/classified_wizard.rb
module Effective
  class ClassifiedWizard < ActiveRecord::Base
    self.table_name = (EffectiveClassifieds.classified_wizards_table_name || :classified_wizards).to_s

    effective_classifieds_classified_wizard
  end
end

app/controllers/admin/classifieds_controller.rb
module Admin
  class ClassifiedsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)
    before_action { EffectiveResources.authorize!(self, :admin, :effective_classifieds) }

    include Effective::CrudController

    submit :save, 'Save'
    submit :save, 'Save and View', redirect: -> { effective_classifieds.classified_path(resource) }
    submit :approve, 'Approve'

    private

    def permitted_params
      model = (params.key?(:effective_classified) ? :effective_classified : :classified)
      params.require(model).permit!
    end

  end
end

app/controllers/effective/classified_submissions_controller.rb
module Effective
  class ClassifiedSubmissionsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)

    include Effective::WizardController

    resource_scope -> { EffectiveClassifieds.ClassifiedSubmission.deep.where(owner: current_user) }

    # Allow only 1 in-progress application at a time
    before_action(only: [:new, :show], unless: -> { resource&.done? }) do
      existing = resource_scope.in_progress.where.not(id: resource).first

      if existing.present?
        flash[:success] = "You have been redirected to your in-progress classified ad submission"
        redirect_to effective_classifieds.classified_submission_build_path(existing, existing.next_step)
      end
    end

    after_save do
      flash.now[:success] = ''
    end

    private

    def permitted_params
      model = (params.key?(:effective_classified_submission) ? :effective_classified_submission : :classified_submission)
      params.require(model).permit!.except(:status, :status_steps, :wizard_steps, :submitted_at)
    end

  end
end

app/controllers/effective/classified_wizards_controller.rb
module Effective
  class ClassifiedWizardsController < ApplicationController
    before_action(:authenticate_user!) if defined?(Devise)

    include Effective::WizardController

    resource_scope -> { EffectiveClassifieds.ClassifiedWizard.deep.where(owner: current_user) }

  end
end

app/controllers/effective/classifieds_controller.rb
module Effective
  class ClassifiedsController < ApplicationController
    include Effective::CrudController

    def index
      EffectiveResources.authorize!(self, :index, ::Effective::Classified)

      @page_title ||= view_context.classifieds_name_label

      @classifieds = ::Effective::Classified.classifieds(user: current_user).sorted
    end

    def show
      @classified = resource_scope.find(params[:id])

      if @classified.respond_to?(:roles_permit?)
        raise Effective::AccessDenied.new('Access Denied', :show, @classified) unless @classified.roles_permit?(current_user)
      end

      EffectiveResources.authorize!(self, :show, @classified)

      if EffectiveResources.authorized?(self, :admin, :effective_classifieds)
        flash.now[:warning] = [
          'Hi Admin!',
          ("You are viewing a hidden #{view_context.classified_label.downcase}." unless @classified.published?),
          ("<a href='#{effective_classifieds.edit_admin_classified_path(@classified)}' class='alert-link'>Edit this #{view_context.classified_label.downcase}</a>.")
        ].compact.join(' ')
      end

      @page_title ||= @classified.to_s

      respond_to do |format|
        format.html { }

        format.json {
          url = effective_classifieds.classified_url(@classified, format: :json)
          render(json: @classified.for_json.merge(url: url).to_json)
        }
      end
    end

    private

    def permitted_params
      params.require(:effective_classified).except(:status, :status_steps).permit!
    end

  end
end

app/views/effective/classifieds/_classified.html.haml
%tr
  %td.col-date.text-right= classified.start_on&.strftime("%b %e, %Y")
  %td
    %strong= link_to classified.title, effective_classifieds.classified_url(classified)
    .text-muted= classified.organization
    .d-block.d-md-none= classified.location

  %td.d-none.d-md-table-cell= classified.location
  -# %td.col-date.d-none.d-md-table-cell.text-right= classified.end_on&.strftime("%b %e, %Y")

app/views/effective/classifieds/_dashboard.html.haml
%h2= classifieds_name_label

- published = Effective::Classified.classifieds(user: current_user).count

- if published > 0
  - datatable = EffectiveClassifiedsDatatable.new(self, namespace: :effective)
  = render_datatable(datatable, simple: true)
- else
  %p There are no active #{classifieds_label.downcase}. When there are, we'll show them here.

%p= link_to 'View All', effective_classifieds.classifieds_path, class: 'btn btn-primary'

app/views/effective/classifieds/_fields.html.haml
= f.select :category, EffectiveClassifieds.categories, required: true, include_blank: false

= render 'effective/classifieds/qb_item_name_field', f: f

= f.text_field :title, label: "#{classified_label} title"
= f.text_field :location, label: "#{classified_label} location"
= f.text_field :organization

- if f.object.persisted? || f.object.errors.include?(:slug)
  - current_url = (effective_classifieds.classified_url(f.object) rescue nil)
  = f.text_field :slug, hint: "The slug controls this resource's internet address. Be careful, changing the slug will break links that other websites may have to the old address.<br>#{('This is currently reachable via ' + link_to(current_url.gsub(f.object.slug, '<strong>' + f.object.slug + '</strong>').html_safe, current_url)) if current_url }".html_safe

- minDate = [Time.zone.now, f.object.created_at].compact.min

.row
  .col-lg-6
    - if f.object.new_record?
      = f.date_field :start_on, label: "Start date", hint: "If approved, this #{classified_label.downcase} will be displayed on the #{classifieds_name_label.downcase} after this date.", input_js: { minDate: minDate.strftime('%F') }
    - else
      = f.date_field :start_on, label: "Start date", hint: "The #{classified_label.downcase} will be displayed starting after this date."

  .col-lg-6
    = f.date_field :end_on, label: "Close date", hint: "The #{classified_label.downcase} will no longer be displayed on the #{classifieds_name_label.downcase} after this date. Please enter a date within #{f.object.end_on_distance} of the start date."

-# - if f.object.persisted? && !f.object.draft?
-#   = f.check_box :archived, label: 'Yes, this posting is archived. It will not be displayed.'

- if defined?(EffectiveArticleEditor)
  = f.article_editor :body, label: 'Description', hint: "The #{classified_label.downcase} description - be sure to include all relevant information!"
- else
  = f.rich_text_area :body, label: 'Description', hint: "The #{classified_label.downcase} description. Be sure to include all relevant information."

= f.file_field :file, label: "Attach a PDF for download. Optional."

%h3.mt-5 Contact Information
%p.text-muted These details <strong>are not</strong> displayed on the #{classifieds_name_label}. They may be used by staff for administration and support. Please ensure the above #{classified_label.downcase} description includes relavent contact information.

= f.text_field :contact_name
= f.url_field :website
= f.email_field :email
= f.tel_field :phone

app/views/effective/classifieds/_form.html.haml
= effective_form_with(model: classified, engine: true) do |f|
  = render('effective/classifieds/fields', f: f, classified: f.object)
  = effective_submit(f)

app/views/effective/classifieds/_layout.html.haml
.effective-classifieds.mb-3
  = yield

app/views/effective/classifieds/_qb_item_name_field.html.haml
- if EffectiveOrders.use_item_names? && EffectiveClassifieds.default_qb_item_name.blank?
  - if controller_path.include?('admin/') && EffectiveResources.authorized?(self, :admin, :effective_classifieds)
    .row
      .col-md-6= qb_item_name_field(f)

app/views/effective/classifieds/_summary.html.haml
= effective_table_with(classified, except: :slug) do |f|
  = render('effective/classifieds/fields', f: f)

app/views/effective/classifieds/edit.html.haml
.card
  .card-body
    = effective_form_with(model: @classified, engine: true) do |f|
      = render('effective/classifieds/fields', f: f, classified: f.object)
      = effective_submit(f)

app/views/effective/classifieds/index.html.haml
= render 'layout' do
  .row
    .col
      %h1.effective-title.mb-4= @page_title

    .col-auto.text-right
      = link_to "Post a #{classified_label}", effective_classifieds.new_classified_wizard_path, class: 'btn btn-primary'

  - if @classifieds.present?
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th.col-date.text-right Posted
            %th Title
            %th.d-none.d-md-table-cell Location
            -# %th.col-date.d-none.d-md-table-cell.text-right Closing

        %tbody
          = render @classifieds

  - else
    .alert.alert-warning.mb-3
      There are no active #{classifieds_label.downcase}.

app/views/effective/classifieds/show.html.haml
= render 'layout' do
  .effective-classified
    - unless @classified.published?
      .alert.alert-warning.mb-4 This #{classified_label} is not published.

    %h1.effective-title.mb-4= @page_title

    .row
      .col-md
        %table.table.table-striped.effective-table-summary
          %tr
            %th Company
            %td= @classified.organization

            - if @classified.location.present?
              %tr
                %th Location
                %td= @classified.location

          %tr
            %th Posted
            %td #{@classified.start_on&.strftime("%b %d, %Y")}

          %tr
            %th Closing
            %td #{@classified.end_on&.strftime("%b %d, %Y")}

          - if @classified.file.attached?
            %tr
              %th Attachment
              %td= link_to(@classified.file.filename, main_app.url_for(@classified.file), target: '_blank')

    .body.mt-4
      = @classified.body.to_s

    = link_to "&larr; #{classifieds_name_label}".html_safe, effective_classifieds.classifieds_path, class: 'btn btn-secondary my-4'